[theme]
base = "light"
primaryColor = "#C62028"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFF7E5"
textColor = "#262730"
font = "sans serif"

[server]
runOnSave = false
baseUrlPath = "catan"
